# Form implementation generated from reading ui file 'DBconDemo.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("DB Handler")
        Form.resize(610, 392)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Create = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Create.setFont(font)
        self.pushButton_Create.setObjectName("pushButton_Create")
        self.pushButton_Create.clicked.connect(self.create_database)
        self.horizontalLayout_2.addWidget(self.pushButton_Create)
        self.pushButton_Connection = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Connection.setFont(font)
        self.pushButton_Connection.setObjectName("pushButton_Connection")
        self.pushButton_Connection.clicked.connect(self.db_connect)
        self.horizontalLayout_2.addWidget(self.pushButton_Connection)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def create_database(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="benjamin",
                password = "Landau1729#"
            )

            cursor = mydb.cursor()
            dbname = self.lineEdit.text()

            cursor.execute("Create Database {}".format(dbname))
            self.label_result.setText("Database {} created".format(dbname))

        except mc.Error as e:
            self.label_result.setText("Database creation failed:\nError {}".format(e))

    def db_connect(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="benjamin",
                password = "Landau1729#",
                database = self.lineEdit.text()
            )

            self.label_result.setText("There is a connection")
        except mc.Error as e:
            self.label_result.setText("Database connection failed:\nError {}".format(e))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("DB Handler", "DB Handler"))
        self.label.setText(_translate("DB Handler", "Name of your database"))
        self.pushButton_Create.setText(_translate("DB Handler", "Create database"))
        self.pushButton_Connection.setText(_translate("DB Handler", "Database connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
