# Form implementation generated from reading ui file 'simple_calculator.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(500, 400)
        self.widget = QtWidgets.QWidget(Calculator)
        self.widget.setGeometry(QtCore.QRect(20, 30, 426, 276))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.number_1 = QtWidgets.QLineEdit(self.widget)
        self.number_1.setObjectName("number_1")
        self.verticalLayout_2.addWidget(self.number_1)
        self.number_2 = QtWidgets.QLineEdit(self.widget)
        self.number_2.setObjectName("number_2")
        self.verticalLayout_2.addWidget(self.number_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.push_button_add = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_button_add.setFont(font)
        self.push_button_add.setObjectName("push_button_add")
        self.push_button_add.clicked.connect(self.add_pushed)
        self.gridLayout_2.addWidget(self.push_button_add, 0, 0, 1, 1)
        self.push_button_subtract = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_button_subtract.setFont(font)
        self.push_button_subtract.setObjectName("push_button_subtract")
        self.push_button_subtract.clicked.connect(self.subtract_pushed)
        self.gridLayout_2.addWidget(self.push_button_subtract, 0, 1, 1, 1)
        self.push_button_multiply = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_button_multiply.setFont(font)
        self.push_button_multiply.setObjectName("push_button_multiply")
        self.push_button_multiply.clicked.connect(self.multiply_pushed)
        self.gridLayout_2.addWidget(self.push_button_multiply, 1, 0, 1, 1)
        self.push_button_divide = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_button_divide.setFont(font)
        self.push_button_divide.setObjectName("push_button_divide")
        self.push_button_divide.clicked.connect(self.divide_pushed)
        self.gridLayout_2.addWidget(self.push_button_divide, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.result = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.gridLayout_4.addWidget(self.result, 1, 0, 1, 1)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.label_1.setText(_translate("Calculator", ""))
        self.label_2.setText(_translate("Calculator", ""))
        self.number_1.setText(_translate("Calculator", ""))
        self.number_2.setText(_translate("Calculator", ""))
        self.push_button_add.setText(_translate("Calculator", "add"))
        self.push_button_subtract.setText(_translate("Calculator", "subtract"))
        self.push_button_multiply.setText(_translate("Calculator", "multiply"))
        self.push_button_divide.setText(_translate("Calculator", "divide"))
        self.result.setText(_translate("Calculator", "Result"))

    def add_pushed(self):
        fnum = float(self.number_1.text())
        snum = float(self.number_2.text())
        result = fnum + snum
        self.result.setText(str(fnum)+'+'+str(snum)+'='+str(result))
    
    def subtract_pushed(self):
        fnum = float(self.number_1.text())
        snum = float(self.number_2.text())
        result = fnum - snum
        self.result.setText(str(fnum)+'-'+str(snum)+'='+str(result))

    def multiply_pushed(self):
        fnum = float(self.number_1.text())
        snum = float(self.number_2.text())
        result = fnum * snum
        self.result.setText(str(fnum)+'*'+str(snum)+'='+str(result))

    def divide_pushed(self):
        fnum = float(self.number_1.text())
        snum = float(self.number_2.text())
        result = fnum / snum
        self.result.setText(str(fnum)+'/'+str(snum)+'='+str(result))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec())
