# Form implementation generated from reading ui file 'extremum_adder.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QInputDialog, QMessageBox, QLineEdit

class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Extremum Adder")
        Dialog.resize(567, 731)
        Dialog.setWindowTitle('Extremum Adder')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_add = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")

        # connect signal
        self.pushButton_add.clicked.connect(self.add_item_push_button)

        self.verticalLayout_2.addWidget(self.pushButton_add)
        self.pushButton_delete = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")

        # connect signal
        self.pushButton_delete.clicked.connect(self.delete_item)

        self.verticalLayout_2.addWidget(self.pushButton_delete)
        self.pushButton_edit = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_edit.setFont(font)
        self.pushButton_edit.setObjectName("pushButton_edit")

        # connect signal
        self.pushButton_edit.clicked.connect(self.edit_item)

        self.verticalLayout_2.addWidget(self.pushButton_edit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton_sort = QtWidgets.QPushButton(Dialog)
        self.pushButton_sort.setObjectName("pushButton_sort")

        # connect signal
        self.pushButton_sort.clicked.connect(self.sort_items)

        self.verticalLayout_2.addWidget(self.pushButton_sort)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_text = QtWidgets.QLineEdit(Dialog)
        self.input_text.setObjectName("input_text")
        
        # connect signal
        self.input_text.returnPressed.connect(self.add_item_enter)

        self.verticalLayout.addWidget(self.input_text)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_add.setText(_translate("Dialog", "add"))
        self.pushButton_delete.setText(_translate("Dialog", "delete"))
        self.pushButton_edit.setText(_translate("Dialog", "edit"))
        self.pushButton_sort.setText(_translate("Dialog", "sort"))

    def add_item_push_button(self):
        
        row = self.listWidget.currentRow()
        title = "Add item"
        data, ok = QInputDialog.getText(self, title, title)

        if(ok and data != None):
            self.listWidget.insertItem(row, data)
    
    def add_item_enter(self):
        self.listWidget.addItem(self.input_text.text())
        self.input_text.setText('')


    def edit_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is not None:
            title = "Edit item"
            data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, item.text())

            if ok and data is not None:
                item.setText(data)

    def delete_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)
        
        if item is None:
            return
        
        reply = QMessageBox.question(self, "Remove Item", "Do you want to remove the "+str(item.text())+" from the list?",
                                    QMessageBox.StandardButton.Yes,QMessageBox.StandardButton.No)
        if reply == QMessageBox.StandardButton.Yes:
            self.listWidget.takeItem(row)

    
    def sort_items(self):
        self.listWidget.sortItems()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
