# Form implementation generated from reading ui file 'CreateDb.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonCreateDb = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCreateDb.setFont(font)
        self.pushButtonCreateDb.setObjectName("pushButtonCreateDb")

        #connect our method to the clicked signal
        self.pushButtonCreateDb.clicked.connect(self.create_database)

        self.horizontalLayout_2.addWidget(self.pushButtonCreateDb)
        self.pushButtonDbCon = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonDbCon.setFont(font)
        self.pushButtonDbCon.setObjectName("pushButtonDbCon")

        #connect our method to the clicked signal
        self.pushButtonDbCon.clicked.connect(self.db_connection)

        self.horizontalLayout_2.addWidget(self.pushButtonDbCon)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.labelResult = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def create_database(self):
        try:
            db = mc.connect(
                host="pyqtexample.clrnsymfz2e0.us-east-1.rds.amazonaws.com",
                user="admin",
                password="password",
                port=3306
            )

            cur = db.cursor()
            dbname = self.lineEdit.text()

            cur.execute("CREATE DATABASE {}".format(dbname))
            self.labelResult.setText("Database {} Created ".format(dbname))

        except mc.Error as e:
            self.labelResult.setText("Database Creation Failed")


    def db_connection(self):
        try:
            db=mc.connect(
                host="pyqtexample.clrnsymfz2e0.us-east-1.rds.amazonaws.com",
                user="admin",
                password="password",
                database="pyqt",
                port=3306
            )

            self.labelResult.setText("We have connection")

        except mc.Error as e:
            self.labelResult.setText("Unable to connect {} ".format(e))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Database Name:"))
        self.pushButtonCreateDb.setText(_translate("Form", "Create Database"))
        self.pushButtonDbCon.setText(_translate("Form", "Database Connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
